sadiki/api/urls.py
# -*- coding: utf-8 -*- 
from django.conf.urls import url, include

from sadiki.api.views import get_distributions, get_distribution, get_child, \
    api_sign_test, get_kindergartens, ChangeRequestionStatus, \
    GetRequestionsByResolution, get_evidience_documents, get_requestions, \
    RequestionsQueue, api_enc_test, get_simple_kindergtns, get_age_groups, \
    GroupsForSadikView, PlacesCount

urlpatterns = [
    # ДОУ
    url(r'^get_kg_info/', get_kindergartens),
    url(r'^sadik/simple_info/', get_simple_kindergtns),
    url(r'^sadik/(?P<sadik_id>\d{1,7})/groups/', GroupsForSadikView.as_view()),

    # Заявки
    url(r'^get_child/', get_child),
    url(r'^requestions_by_resolution/', GetRequestionsByResolution.as_view()),
    url(r'^change_requestion_status/', ChangeRequestionStatus.as_view()),
    url(r'^get_requestions/', RequestionsQueue.as_view()),

    # Распределения
    url(r'^get_distributions/$', get_distributions),
    url(r'^get_distribution/', get_distribution),
    url(r'^distributions/places/total/', PlacesCount.as_view()),

    # остальное
    url(r'^sign_test/', api_sign_test),
    url(r'^enc_test/', api_enc_test),
    url(r'^get_evidience_documents/', get_evidience_documents),
    url(r'^age_groups/', get_age_groups),
]

sadiki/authorisation/urls.py
# -*- coding: utf-8 -*- 
from django.conf.urls import url
from forms import LoginForm

from django.contrib.auth import views as auth_views
from sadiki.authorisation.views import (password_set, EmailVerification,
    ResetPassword, ResetPasswordRequest,
    send_confirm_letter, login_with_error_handling)


urlpatterns = [
    url(r'^login/$', login_with_error_handling, {
        'template_name': 'authorisation/login.html',
        'authentication_form': LoginForm}, name='login'),
    url(r'^passwd_set/$', password_set, name='passwd_set'),
    url(r'^send_confirm/$', send_confirm_letter, name='send_confirm_letter'),
    url(r'^email_verification/(?P<key>\w{40})/$',
        EmailVerification.as_view(), name='email_verification'),
    url(r'^reset_password_request/$',
        ResetPasswordRequest.as_view(), name='reset_password_request'),
    url(r'^reset_password/(?P<key>\w{40})/$',
        ResetPassword.as_view(), name='reset_password'),
    url(r'^passwd/$', auth_views.password_change,
        {'template_name': 'authorisation/passwd.html'}, name='passwd'),
    url(r'^passwd/done/$', auth_views.password_change_done,
        {'template_name': 'authorisation/passwd_done.html'},
        name='password_change_done'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/', }, name="logout"),
]

sadiki/core/urls.py
# -*- coding: utf-8 -*- 
from django.conf.urls import url, include
from django.contrib import admin
from .views import Frontpage, sadiki_json, registration, queue, search, import_params, \
    GetCoordsFromAddress
from sadiki.anonym.views import QueueMap

urlpatterns = [
    url(r'^$', Frontpage.as_view(), name='frontpage'),
    url(r'^api/sadiki.json$', sadiki_json, name='sadiki_json'),
    url(r'^registration/$', registration, name=u'anonym_registration'),
    url(r'^queue/$', queue, name=u'anonym_queue'),
    url(r'^queuemap/$', QueueMap.as_view(), name=u'queue_map'),
    url(r'^get_coords/$',
        GetCoordsFromAddress.as_view(), name='get_coords_from_address'),
    url(r'^requestion_search/$', search, name=u'anonym_requestion_search'),
    url(r'^import_params/$', import_params, name='import_params_json'),

    url(r'^admin/', include(admin.site.urls), name="default_admin"),
]

sadiki/operator/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt
from sadiki.operator.plugins import plugins

from sadiki.operator.views.requestion import FrontPage, RequestionInfo, \
    RequestionAdd, ConfirmEmail, EmailChange ,\
    RequestionStatusChange, SetIdentityDocument, FindProfileForRequestion, \
    EmbedRequestionToProfile, GenerateBlank, GenerateProfilePassword, ChangeRequestionLocation, ProfileInfo, SocialProfilePublic
from sadiki.operator.views.sadik import SadikListWithGroups, SadikGroupChangePlaces, \
    RequestionListEnrollment, SadikInfoChange, DistributedRequestionsForSadik, \
    SadikListWithGroupsJS


urlpatterns = [
    # Общие функции
    url(r'^$', FrontPage.as_view(), name='operator_frontpage'),

    #профиль
    url(r'^profile/(?P<profile_id>\d{1,7})/$',
        ProfileInfo.as_view(), name=u'operator_profile_info'),
    url(r'^profile/(?P<profile_id>\d{1,7})/requestion_add/$',
        RequestionAdd.as_view(), name=u'operator_requestion_add'),
    url(r'^profile/(?P<profile_id>\d{1,7})/generate_profile_password/$',
        GenerateProfilePassword.as_view(), name=u'generate_profile_password'),
    url(r'^social_profile_public/(?P<profile_id>\d{1,7})/$',
        SocialProfilePublic.as_view(), name='operator_social_profile_public'),
    url(r'^profile/(?P<profile_id>\d{1,7})/save_email/$',
        EmailChange.as_view(), name=u'change_profile_email'),
    url(r'^profile/(?P<profile_id>\d{1,7})/confirm_email/$',
        ConfirmEmail.as_view(), name=u'confirm_profile_email'),

    # Работа с конкретной заявкой
    url(r'^request/(?P<requestion_id>\d{1,7})/$',
        RequestionInfo.as_view(), name=u'operator_requestion_info'),
    url(r'^request/(?P<requestion_id>\d{1,7})/set_identity_document/$',
        SetIdentityDocument.as_view(), name=u'operator_requestion_set_identity_document'),
    url(r'^request/(?P<requestion_id>\d{1,7})/find_profile/$',
        FindProfileForRequestion.as_view(), name=u'find_profile_for_requestion'),
    url(r'^request/(?P<requestion_id>\d{1,7})/embed_to_profile/(?P<profile_id>\d{1,7})/$',
        EmbedRequestionToProfile.as_view(), name=u'embed_requestion_to_profile'),
    url(r'^request/(?P<requestion_id>\d{1,7})/change_location/$',
        ChangeRequestionLocation.as_view(), name=u'change_requestion_location'),
    # Смена статуса заявки
    url(r'^request/(?P<requestion_id>\d{1,7})/status-(?P<dst_status>\d{1,3})/$',
        RequestionStatusChange.as_view(), name=u'operator_requestion_status_change'),
    url(r'^request/(?P<requestion_id>\d{1,7})/generate_blank/$',
        GenerateBlank.as_view(), name=u'operator_generate_blank'),

    # Работа с садиками
    url(r'^dou/$',
        SadikListWithGroups.as_view(), name=u'sadik_list_with_groups'),
    url(r'^doujs/$',
        SadikListWithGroupsJS.as_view(), name=u'sadik_list_with_groups_js'),
    url(r'^dou/(?P<sadik_id>\d{1,7})/change_info/$',
        SadikInfoChange.as_view(), name=u'sadik_info_change'),
    url(r'^dou/(?P<sadik_id>\d{1,7})/places/$',
        SadikGroupChangePlaces.as_view(), name=u'sadikgroup_change_places'),
    url(r'^dou/(?:(?P<sadik_id>\d{1,7})/)?requests/$',
        RequestionListEnrollment.as_view(), name=u'requestion_list_enroll'),
    url(r'^dou/(?P<sadik_id>\d{1,7})/distributed_requestions/$',
        DistributedRequestionsForSadik.as_view(), name=u'distributed_requestions_for_sadik'),
]

for plugin in plugins:
    try:
        urlpatterns += plugin.get_urls()
    except NotImplementedError:
        pass

sadiki/operator/models.py
# -*- coding: utf-8 -*-

sadiki/account/forms.py
# -*- coding: utf-8 -*-
import datetime

from django import forms
from django.conf import settings
from django.forms.models import ModelForm
from django.forms.models import BaseModelFormSet
from django.forms.utils import ErrorList
from django.contrib.auth.models import User
from sadiki.anonym.forms import FormWithDocument, TemplateFormField
from sadiki.core.fields import SadikWithAreasNameField
from sadiki.core.geo_field import location_errors
from sadiki.core.models import Profile, Requestion, Sadik, REQUESTION_IDENTITY,\
    Benefit, PersonalDocument
from sadiki.core.widgets import JqueryUIDateWidget, SelectMultipleJS, \
    JQueryUIAdmissionDateWidget, JqueryIssueDateWidget, SelectMultipleBenefits
from sadiki.core.widgets import SnilsWidget
from sadiki.core.validators import passport_series_validator
from sadiki.core.validators import passport_number_validator, phone_validator


class RequestionForm(FormWithDocument):
    template = TemplateFormField(
        destination=REQUESTION_IDENTITY, label=u'Тип документа')
    pref_sadiks = SadikWithAreasNameField(
        queryset=Sadik.objects.filter(
            active_registration=True).select_related('area'),
        required=True, widget=SelectMultipleJS(),)
    kinship_type = forms.ChoiceField(
        label=u'Степень родства заявителя',
        choices=Requestion.REQUESTER_TYPE_CHOICES)
    token = forms.CharField(widget=forms.HiddenInput())

    class Meta:
        model = Requestion
        _base_fields = ['areas', 'name', 'child_last_name', 'child_middle_name',
                        'token', 'birth_date', 'sex', 'template',
                        'birthplace', 'kinship_type', 'kinship',
                        'child_snils', 'document_number', 'district',
                        'pref_sadiks', 'location', 'admission_date']
        if settings.DESIRED_SADIKS == settings.DESIRED_SADIKS_CHOICE:
            _base_fields = _base_fields + ['distribute_in_any_sadik',]
        fields = _base_fields

    def __init__(self, *args, **kwds):
        self.base_fields['areas'].help_text = None
        self.base_fields['location'].label = u'Укажите ваше местоположение'
        self.base_fields['location'].help_text = (
            u'Относительно этого '
            u'местоположения оператор будет подбирать ближайший детский сад '
            u'из выбранных групп ДОУ, если в приоритетных ДОУ не останется '
            u'свободных мест. Введите адрес в строку поиска, нажмите кнопку. '
            u'Далее кликните на иконке маркера и перетащите маркер в нужную '
            u'точку на карте.')
        self.base_fields['location'].required = True
        self.base_fields['location'].error_messages.update(location_errors)
        self.base_fields['template'].help_text = u"Документ, идентифицирующий\
            ребёнка"
        self.base_fields['birth_date'].widget = JqueryUIDateWidget()
        self.base_fields['admission_date'].widget = JQueryUIAdmissionDateWidget()
        self.base_fields['admission_date'].required = True
        self.base_fields['admission_date'].initial = datetime.date.today()
        self.base_fields['kinship'].label = (u'Укажите, кем приходится'
                                             u' заявитель ребёнку')
        self.base_fields['child_snils'].widget = SnilsWidget()
        self.base_fields['pref_sadiks'].label = u'Выберите ДОУ'
        self.base_fields['pref_sadiks'].help_text = (
            u'Нежелательно выбирать '
            u'более 3-х учреждений. Приоритетные детские сады могут находиться'
            u' в разных группах ДОУ. Список приоритетных ДОУ не даёт прав на '
            u'внеочередное зачисление в выбранные ДОУ.')
        self.base_fields['areas'].label = u'Выберите группы ДОУ'
        self.base_fields['areas'].help_text = (
            u'Все детские сады муниципалитета объединены '
            u'в группы по территориальному признаку. Вы можете выбрать '
            u'несколько групп ДОУ, количество не ограничено. От выбора групп '
            u'ДОУ будет зависеть участие вашей заявки в комплектовании. При '
            u'комплектовании ваша заявка будет претендовать только в '
            u'учреждения выбранных групп ДОУ и приоритетные детские сады. '
            u'Учреждения выбранной группы ДОУ на карте окрашиваются в желтый '
            u'цвет. Изменив масштаб карты, можно оценить территорию, '
            u'охваченную выбранными группами ДОУ.')
        self.base_fields['district'].label = u'Выберите район'
        super(RequestionForm, self).__init__(*args, **kwds)

    def clean_birthplace(self):
        return self.cleaned_data.get('birthplace').strip()

    def clean_kinship(self):
        return self.cleaned_data.get('kinship').strip()

    def clean(self, *args, **kwargs):
        kinship_type = self.cleaned_data.get('kinship_type')
        if kinship_type and kinship_type != Requestion.REQUESTER_TYPE_OTHER:
            self.cleaned_data['kinship'] = dict(
                Requestion.REQUESTER_TYPE_CHOICES).get(kinship_type)
        if not self.cleaned_data['kinship']:
            kinship_errors = self._errors.setdefault('kinship', ErrorList())
            kinship_errors.append(u'Это поле обязательно.')
        self.cleaned_data['distribute_in_any_sadik'] = True
        admission_date = self.cleaned_data.get('admission_date')
        admission_date_error = False
        if admission_date:
            today = datetime.date.today()
            if admission_date < today:
                admission_date_error = True
            birth_date = self.cleaned_data.get('birth_date')
            if birth_date and admission_date < birth_date:
                admission_date_error = True
        if admission_date_error:
            admission_date_errors = self._errors.setdefault(
                'admission_date', ErrorList())
            admission_date_errors.append(
                u'Не может быть меньше текущей даты '
                u'и меньше даты рождения ребёнка.')
        return super(RequestionForm, self).clean(*args, **kwargs)

    def save(self, profile, commit=True):
        requestion = super(RequestionForm, self).save(commit=False)
        requestion.profile = profile
        if commit:
            requestion.save()
            self.save_m2m()
            self.instance.document = self.create_document(requestion)
        return requestion


class ChangeRequestionForm(forms.ModelForm):
    kinship_type = forms.ChoiceField(
        label=u'Степень родства заявителя',
        choices=Requestion.REQUESTER_TYPE_CHOICES)

    class Meta:
        model = Requestion
        fields = ('name', 'sex', 'location', 'admission_date', 'district',
                  'child_middle_name', 'child_last_name',
                  'birthplace', 'kinship_type', 'kinship', 'child_snils',)

    def __init__(self, *args, **kwds):
        self.base_fields['location'].required = True
        self.base_fields['location'].label = u'Ваше местоположение'
        self.base_fields['location'].error_messages.update(location_errors)
        self.base_fields['admission_date'].widget = JQueryUIAdmissionDateWidget()
        self.base_fields['kinship'].label = (u'Укажите, кем приходится'
                                             u' заявитель ребёнку')
        self.base_fields['child_snils'].widget = SnilsWidget()
        self.base_fields['location'].help_text = (
            u'Относительно этого местоположения оператор '
            u'будет подбирать ближайший детский сад из выбранных групп ДОУ, '
            u'если в приоритетных ДОУ не останется свободных мест. Для '
            u'изменения местоположения наведите курсор мыши на маркер и '
            u'перетащите маркер, зажав левую клавишу мыши. Не забудьте '
            u'сохранить изменения.')
        super(ChangeRequestionForm, self).__init__(*args, **kwds)

    def clean_birthplace(self):
        return self.cleaned_data.get('birthplace').strip()

    def clean_kinship(self):
        return self.cleaned_data.get('kinship').strip()

    def clean(self, *args, **kwargs):
        kinship_type = self.cleaned_data.get('kinship_type')
        if kinship_type and kinship_type != Requestion.REQUESTER_TYPE_OTHER:
            self.cleaned_data['kinship'] = dict(
                Requestion.REQUESTER_TYPE_CHOICES).get(kinship_type)
        if (self.cleaned_data['kinship'] == self.instance.kinship
                and 'kinship' in self.changed_data):
            self.changed_data.remove('kinship')
        if 'kinship_type' in self.changed_data:
            self.changed_data.remove('kinship_type')
        if not self.cleaned_data['kinship']:
            kinship_errors = self._errors.setdefault('kinship', ErrorList())
            kinship_errors.append(u'Это поле обязательно.')
        admission_date = self.cleaned_data.get('admission_date')
        admission_date_error = False
        if admission_date:
            today = datetime.date.today()
            if admission_date < today:
                admission_date_error = True
            birth_date = self.cleaned_data.get('birth_date')
            if birth_date and admission_date < birth_date:
                admission_date_error = True
        if admission_date_error:
            admission_date_errors = self._errors.setdefault(
                'admission_date', ErrorList())
            admission_date_errors.append(
                u'Не может быть меньше текущей даты '
                u'и меньше даты рождения ребёнка.')
        return super(ChangeRequestionForm, self).clean(*args, **kwargs)


class BenefitsForm(forms.ModelForm):

    benefits = forms.ModelMultipleChoiceField(
        label=u'Льготы для заявки', 
        queryset=Benefit.objects,
        widget=SelectMultipleBenefits(), required=False,
        help_text=u'Выбранные льготы недействительны без документального '
                  u'подтверждения',
    )

    class Meta:
        model = Requestion
        fields = ('benefits',)


class PreferredSadikForm(forms.ModelForm):

sadiki/operator/templates/operator/includes/benefits_documents_change_js.html
<script type="text/javascript" src="{{ STATIC_URL }}js/libs/underscore.js"></script>
<script type="text/javascript">
    function removeDocumentForm(field){
{#            удаление документа, вызывается при ручном и автоматическом удалении#}
        field.find('input[id $= "-DELETE"]').attr('checked', true);
        field.find('.field-value input[id $= "-document_number"]').val('');
        field.find('.field-value label.value').text('Не указано')
        field.find('.field-label').removeClass('changed')
        field.find('.field-label .value-changed').remove()
        field.hide()
    }
{#        удаление документа вручную#}
    function manualRemoveDocumentForm(el){
        removeDocumentForm($(el).parents('.field'))
    }
    function cloneDocumentForm(selector, type, documentTemplate) {
{#            добавление формы документа#}
        var newElement = $(selector).clone(true);
        newElement.removeClass('original-form')
        var total = $('#id_' + type + '-TOTAL_FORMS').val();
        newElement.find(':input').each(function() {
            var name = $(this).attr('name').replace(/-\d-/,'-' + total + '-');
            var id = 'id_' + name;
            $(this).attr({'name': name, 'id': id})
        });
{#            задаем необходимый шаблон документа#}
        newElement.find('label.field-label').text(documentTemplate.name);
        var templateInput = newElement.find('input[id $= "-template"]');
        templateInput.val(documentTemplate['id'])
        total++;
        $('#id_' + type + '-TOTAL_FORMS').val(total);
        newElement.hide();
        $(selector).parent().append(newElement);
        newElement.show();
        return newElement
    };
    function autoRemoveDocumentForm(documentTemplate){
{#            автоматическое удаление документа, если не задан номер#}
        var field = $('.documents-form input[value='+documentTemplate['id']+'][id $= "-template"]').parents('.field');
        if (!field.find('.field-value input[id $= "-document_number"]').val()){
            removeDocumentForm(field);
        } else {
            if (!field.find('.delete-form').length){
                field.find('.field-value').append('<a class="delete-form" onclick="manualRemoveDocumentForm(this)" href="javascript:void(0)"><i class="red icon-remove">&nbsp;</i></a>')
            }
        }
    }
    var documentTemplates = _.values(DOCUMENT_TEMPLATES);
    function benefits_changed(el){
        var selectedBenefits = _.map($(el).val(), function(item){return Number(item)});
        var requiredTemplates = _.filter(
            documentTemplates, function(item){
                return _.intersection(item.benefits, selectedBenefits).length > 0;
        });
        var templateElements = $('.field').not(':hidden').find('input[id $= "-template"]');
        var documentListIds = _.map(templateElements, function(item){return Number($(item).val())});
        var documentList = _.filter(documentTemplates, function(item){return _.contains(documentListIds, item.id)})
{#            отсутствующие документы#}
        var absentDocuments = _.difference(requiredTemplates, documentList);
{#        если документ уже отображается, то убрать возможность его удалить#}
        for (var i = 0; i < documentList.length; i++) {
            var field = $('.documents-form input[value='+documentList[i].id+'][id $= "-template"]').parents('.field')
            field.find('.delete-form').remove()
        }
        for (var i = 0; i < absentDocuments.length; i++) {
{#                если элемент уже существует, то его нужно отобразить#}
            var field = $('.documents-form input[value='+absentDocuments[i].id+'][id $= "-template"]').parents('.field')
            if (field.length){
                field.find('input[id $= "-DELETE"]').attr('checked', false);
                field.show()
                field.find('.delete-form').remove()
            } else {
{#                    иначе добавить#}
                field = cloneDocumentForm('.documents-form .original-form', 'core-evidiencedocument-content_type-object_id', absentDocuments[i]);
            }
        }
        var notRequiredDocuments = _.difference(documentList, requiredTemplates)
        for (var i = 0; i < notRequiredDocuments.length; i++){
            autoRemoveDocumentForm(notRequiredDocuments[i])
        }
{#        для всех существующих документов нужно задать подсказку и валидацию по формату#}
        $(".documents-form .field:not(.original-form)").each(function (){
            var templateInput = $(this).find('input[id $= "-template"]')
            var documentTemplate = DOCUMENT_TEMPLATES[templateInput.val()]
            var documentInput = $(this).find('input[id $= "-document_number"]')
            change_document_hint(documentInput, documentTemplate['help_text'], 'hint');
            bind_new_regexp(documentInput, documentTemplate['regexp'], 'hint');
        })
    };
    $(document).ready(function(){
        $("#id_benefits").change(function(){
            benefits_changed(this);
        })
        benefits_changed("#id_benefits")
    })
</script>

sadiki/operator/templates/operator/includes/documents_formset.html
{{ formset.management_form }}
{% for form in formset.forms %}
    <div class="{% if not form.template.value %}original-form {% endif %}{% if form.errors %}error {% endif %}field">
        <label class="field-label">{{ form.instance.template }}{% if form.errors %}<span class="value-changed"> ({% for field in form %}{{ field.errors|striptags }}{% endfor %}{{ form.non_field_errors|striptags }})</span>{% endif %}</label>
        {{ form.id }}
        {{ form.template }}
        {{ form.DELETE }}
        <p class="field-value hidden-input">
            <label class="value">{{ form.document_number.value|default:"Не указано" }}</label>
            {{ form.document_number }}
            <a href="#" onclick="change_field(this); return false"><img src="{{ STATIC_URL }}img/icon_edit.fw.png"/></a>
        </p>
        <p class="hint">&nbsp;</p>
    </div>
{% endfor %}

sadiki/operator/templates/operator/includes/queue_include.html
{% extends "anonym/includes/queue_include.html" %}

{% block requestion_number %}<a href="{% url 'operator_requestion_info' requestion.id %}">{{ requestion.requestion_number }}</a>{% endblock %}

sadiki/operator/templates/operator/includes/requestion_menu.html
{% load sadiki_core_tags %}
{% load_urlpatterns %}
{% url 'anonym_requestion_search' as requestion_search_url %}
<ul class="content-menu">
    {% url 'operator_profile_info' profile_id=profile.id as profile_url %}
    {% url 'operator_requestion_add' profile_id=profile.id as operator_requestion_add_url %}
    {% url 'operator_logs' profile_id=profile.id as operator_logs_url %}
    <li {% if request.path == profile_url %}class="active"{% endif %}>
        <a href="{{ profile_url }}">Профиль</a>
    </li>
    {% for requestion in profile.requestion_set.all|dictsort:"id" %}
        {% url 'operator_requestion_info' requestion.id as operator_requestion_info_url %}
        <li {% if request.path == operator_requestion_info_url %}class="active"{% endif %}>
            <a href="{{ operator_requestion_info_url }}">{{ requestion.requestion_number }}</a>
        </li>
    {% endfor %}
    <li {% if request.path == operator_requestion_add_url %}class="active"{% endif %}>
        <a href="{{ operator_requestion_add_url }}">Добавить заявку
            <img class='requestion-add-menu' src="{{ STATIC_URL }}img/requestion_add_menu.png"/>
        </a>
    </li>
    {% for url, name in plugin_menu_items.iteritems %}
        <li {% if request.path == url %}class="active"{% endif %}>
            <a href="{{ url }}">{{ name }}</a>
        </li>
    {% endfor %}
    <li {% if request.path == operator_logs_url %}class="active"{% endif %}>
        <a href="{{ operator_logs_url }}">История изменений</a>
    </li>
</ul>

sadiki/operator/templates/operator/includes/requestion_search_include.html
{% load sadiki_core_tags zenforms pytils_numeral %}

<div class="content-main">
    {% zenform form %}
        <div class="row">
            <div class="span5">
                {% fieldset 'child_last_name' 'child_name' 'child_middle_name' 'number_in_old_list' 'registration_date' 'requester_last_name' 'requester_first_name' 'requester_middle_name' 'requester_document_series' 'requester_document_number' %}
            </div>
            <div class="span5">
                {% fieldset 'document_number' 'requestion_number' 'birth_date' %}
            </div>
        </div>
        <div class="row">
            <div class="span10">
                {% submit "Поиск" %}
            </div>
        </div>
    {% endzenform %}
    {% if query %}
        <div class="row vertical-margins"><div class="span10">
            <div class="well query">
                По запросу:
                {% for field in query.fields.values %}
                    <dl>
                        <dt>{{ field.label }}</dt>
                        <dd>{{ field.value }}</dd>
                    </dl>
                {% endfor %}
                <strong>{{ results.count }} заяв{{ results.count|choose_plural:"ка, ки, ок" }}</strong>
            </div>
            {% if results.count > 0 %}
                {% block queue_table %}
                    <table class="table table-striped table-bordered table-condensed">
                        <thead>
                        <tr>
                            <th>№</th>
                            <th>Номер заявки</th>
                            <th>Дата рождения</th>
                            <th>Дата регистрации</th>
                            <th>Льготы</th>
                            <th>Статус заявки</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for requestion in results %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td><a href="{% url 'operator_requestion_info' requestion_id=requestion.id %}">{{ requestion.requestion_number }}</a></td>
                                <td>{{ requestion.birth_date }}</td>
                                <td>{{ requestion.registration_datetime }}</td>
                                <td>{{ requestion.benefit_category }}</td>
                                <td>{{ requestion.get_status_display }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% endblock queue_table %}
            {% else %}
                {% if more_results.count > 0 %}
                    <div class="well query">
                        Но зато по запросу:
                        {% for field in less_query.fields.values %}
                            <dl>
                                <dt>{{ field.label }}</dt>
                                <dd>{{ field.value }}</dd>
                            </dl>
                        {% endfor %}
                        <strong>{{ more_results.count }} заяв{{ more_results.count|choose_plural:"ка, ки, ок" }}</strong>
                    </div>
                {% endif %}
            {% endif %}
        </div></div>
    {% endif %}
</div>

sadiki/operator/templates/operator/includes/sadik_info_distributed_include.html
{% extends "anonym/includes/sadik_info_distributed_include.html" %}

{% block requestion_number %}
    <a href="{% url 'operator_requestion_info' requestion.id %}">{{ requestion }}</a>
{% endblock %}