sadiki/anonym/urls.py
# -*- coding: utf-8 -*- 
from django.conf.urls import url
from sadiki.anonym.views import Frontpage, SadikInfo, SadikList, SadikiMap


urlpatterns = [
    url(r'^$', Frontpage.as_view(), name=u'anonym_frontpage'),
    url(r'^sadik/$', SadikList.as_view(),
        name=u'sadik_list'),
    url(r'^sadik/(?P<sadik_id>\d{1,7})/$', SadikInfo.as_view(),
        name=u'sadik_info'),
    url(r'^map/', SadikiMap.as_view(), 
    	name='sadiki_map'),
]

sadiki/api/urls.py
# -*- coding: utf-8 -*- 
from django.conf.urls import url, include

from sadiki.api.views import get_distributions, get_distribution, get_child, \
    api_sign_test, get_kindergartens, ChangeRequestionStatus, \
    GetRequestionsByResolution, get_evidience_documents, get_requestions, \
    RequestionsQueue, api_enc_test, get_simple_kindergtns, get_age_groups, \
    GroupsForSadikView, PlacesCount

urlpatterns = [
    # ДОУ
    url(r'^get_kg_info/', get_kindergartens),
    url(r'^sadik/simple_info/', get_simple_kindergtns),
    url(r'^sadik/(?P<sadik_id>\d{1,7})/groups/', GroupsForSadikView.as_view()),

    # Заявки
    url(r'^get_child/', get_child),
    url(r'^requestions_by_resolution/', GetRequestionsByResolution.as_view()),
    url(r'^change_requestion_status/', ChangeRequestionStatus.as_view()),
    url(r'^get_requestions/', RequestionsQueue.as_view()),

    # Распределения
    url(r'^get_distributions/$', get_distributions),
    url(r'^get_distribution/', get_distribution),
    url(r'^distributions/places/total/', PlacesCount.as_view()),

    # остальное
    url(r'^sign_test/', api_sign_test),
    url(r'^enc_test/', api_enc_test),
    url(r'^get_evidience_documents/', get_evidience_documents),
    url(r'^age_groups/', get_age_groups),
]

sadiki/authorisation/urls.py
# -*- coding: utf-8 -*- 
from django.conf.urls import url
from forms import LoginForm

from django.contrib.auth import views as auth_views
from sadiki.authorisation.views import (password_set, EmailVerification,
    ResetPassword, ResetPasswordRequest,
    send_confirm_letter, login_with_error_handling)


urlpatterns = [
    url(r'^login/$', login_with_error_handling, {
        'template_name': 'authorisation/login.html',
        'authentication_form': LoginForm}, name='login'),
    url(r'^passwd_set/$', password_set, name='passwd_set'),
    url(r'^send_confirm/$', send_confirm_letter, name='send_confirm_letter'),
    url(r'^email_verification/(?P<key>\w{40})/$',
        EmailVerification.as_view(), name='email_verification'),
    url(r'^reset_password_request/$',
        ResetPasswordRequest.as_view(), name='reset_password_request'),
    url(r'^reset_password/(?P<key>\w{40})/$',
        ResetPassword.as_view(), name='reset_password'),
    url(r'^passwd/$', auth_views.password_change,
        {'template_name': 'authorisation/passwd.html'}, name='passwd'),
    url(r'^passwd/done/$', auth_views.password_change_done,
        {'template_name': 'authorisation/passwd_done.html'},
        name='password_change_done'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/', }, name="logout"),
]

sadiki/core/urls.py
# -*- coding: utf-8 -*- 
from django.conf.urls import url, include
from django.contrib import admin
from .views import Frontpage, sadiki_json, registration, queue, search, import_params, \
    GetCoordsFromAddress
from sadiki.anonym.views import QueueMap

urlpatterns = [
    url(r'^$', Frontpage.as_view(), name='frontpage'),
    url(r'^api/sadiki.json$', sadiki_json, name='sadiki_json'),
    url(r'^registration/$', registration, name=u'anonym_registration'),
    url(r'^queue/$', queue, name=u'anonym_queue'),
    url(r'^queuemap/$', QueueMap.as_view(), name=u'queue_map'),
    url(r'^get_coords/$',
        GetCoordsFromAddress.as_view(), name='get_coords_from_address'),
    url(r'^requestion_search/$', search, name=u'anonym_requestion_search'),
    url(r'^import_params/$', import_params, name='import_params_json'),

    url(r'^admin/', include(admin.site.urls), name="default_admin"),
]

sadiki/anonym/forms.py
# -*- coding: utf-8 -*-
import re
from datetime import timedelta

from django import forms
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _

from sadiki.conf_settings import REQUESTION_NUMBER_MASK
from sadiki.core.fields import TemplateFormField, DateRangeField
from sadiki.core.models import Requestion, PROFILE_IDENTITY, Profile, \
    EvidienceDocument, REQUESTION_IDENTITY, AgeGroup, BenefitCategory, Area, \
    STATUS_CHOICES_FILTER, STATUS_KG_LEAVE
from sadiki.core.utils import get_unique_username, active_child_exist
from sadiki.core.widgets import JqueryUIDateWidget
from sadiki.core.utils import reorder_fields


# STATUS_CHOICES_EMPTY = (('', '---------'), ) + STATUS_CHOICES


class RegistrationForm(forms.ModelForm):
    u"""Форма регистрации для создания пользователя"""
    password1 = forms.CharField(
        label=_("Password"), widget=forms.PasswordInput(
            attrs={'placeholder':
                   u"Введите пароль для регистрации в электронной очереди"}))
    password2 = forms.CharField(
        label=_("Password confirmation"), widget=forms.PasswordInput(
            attrs={'placeholder':
                   u"Введите тот же пароль, что и выше, для подтверждения"}))
    pdata_processing_permit = forms.BooleanField(
        label=u"Я даю согласие на обработку персональных данных",
        required=True)


    class Meta:
        model = User
        fields = ('password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)

    def clean_password1(self):
        if 'password1' in self.cleaned_data:
            password = self.cleaned_data['password1']
            # проверка, что Email и пароль не совпадают
            if 'username' in self.cleaned_data:
                if password == self.cleaned_data['username']:
                    raise forms.ValidationError(
                        u'Пароль не может совпадать с адресом электронной почты')
            # проверка длины пароля
            if len(password) <= 4:
                raise forms.ValidationError(u'Слишком короткий пароль')

        return self.cleaned_data['password1']

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1", "")
        password2 = self.cleaned_data["password2"]
        if password1 != password2:
            raise forms.ValidationError(u"Введенные пароли не совпадают")
        return password2

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.username = get_unique_username()
        password = self.cleaned_data.get('password1')
        if password:
            user.set_password(password)
        if commit:
            user.save()
        return user


class FormWithDocument(forms.ModelForm):
    template = TemplateFormField(
        destination=PROFILE_IDENTITY, label=u'Тип документа',
        help_text=u"Документ, удостоверяющий личность представителя ребенка")
    document_number = forms.CharField(
        label=u'Серия и номер документа', max_length=255,
        widget=forms.TextInput(attrs={'autocomplete': 'off'}))

    def create_document(self, requestion, commit=True):
        document = EvidienceDocument(
            template=self.cleaned_data.get('template'),
            document_number=self.cleaned_data.get('document_number'),
            object_id=self.instance.id,
            content_type=ContentType.objects.get_for_model(self.instance)
            )
        if commit:
            document.save()
        return document

    def clean(self):
        cleaned_data = self.cleaned_data
        document_number = self.cleaned_data.get('document_number')
        template = self.cleaned_data.get('template')
        # проверяем, что номер документа соответствует шаблону
        if document_number and template and not re.match(
            template.regex, document_number):
            self._errors["document_number"] = self.error_class([u'Неверный формат'])
            del cleaned_data['document_number']
            del cleaned_data['template']
        # проверяем на наличие подтвержденных заявок с таким же документом
        else:
            documents = EvidienceDocument.objects.filter(
                document_number=document_number, confirmed=True,
                template=template)
            if documents:
                requestions_ids = documents.values_list('object_id', flat=True)
                # заявки в статусе "Выпущен из ДОУ" могут содержать
                # повторяющиеся номера документов
                requestions = Requestion.objects.filter(
                    id__in=requestions_ids).exclude(status=STATUS_KG_LEAVE)
                if requestions.exists():
                    self._errors["document_number"] = self.error_class(
                        [u"Документ с таким номером уже занят"])
                    del cleaned_data['document_number']
                    # возвращаем значение, чтобы не выполнять ненужных проверок
                    # на наличие ребенка в ЭС
                    return cleaned_data
            # проверяем по номеру документа наличие и статус ребенка в ЭС
            if active_child_exist(document_number):
                self._errors["document_number"] = self.error_class(
                    [u"Ребенок с таким документом уже посещает ДОУ"])
                del cleaned_data['document_number']
        return cleaned_data


class PublicSearchForm(forms.Form):
    birth_date = forms.DateField(
        label=u'Дата рождения ребёнка',
        widget=JqueryUIDateWidget(), required=True)
    registration_date = forms.DateField(
        label=u'Дата регистрации заявки', widget=JqueryUIDateWidget(), required=False)
    number_in_old_list = forms.CharField(
        label=u'Номер в списке у заявок, поданных до запуска системы',
        required=False, widget=forms.TextInput())
    document_number = forms.CharField(
        label=u'Номер свидетельства о рождении', required=False,
        widget=forms.TextInput(), help_text=u'Формат: II-ИВ 123456')
    child_name = forms.CharField(
        label=u'Имя ребёнка', required=False, widget=forms.TextInput())

    field_map = {
        'birth_date': 'birth_date__exact',
        'registration_date': 'registration_datetime__range',
        'number_in_old_list': 'number_in_old_list__exact',
        'child_name': 'name__icontains',
        'document_number': 'id__in'
    }

    def __init__(self, *args, **kwds):
        super(PublicSearchForm, self).__init__(*args, **kwds)
        self.reverse_field_map = dict((v, k) for k, v in self.field_map.iteritems())

    def build_query(self):
        if self.cleaned_data:
            filter_kwargs = {}
            if 'birth_date' in self.changed_data:
                filter_kwargs[self.field_map['birth_date']] = self.cleaned_data['birth_date']
            if 'registration_date' in self.changed_data:
                filter_kwargs[self.field_map['registration_date']] = (
                    self.cleaned_data['registration_date'],
                    self.cleaned_data['registration_date'] + timedelta(days=1),
                )
            if 'number_in_old_list' in self.changed_data:
                filter_kwargs[self.field_map['number_in_old_list']] = self.cleaned_data['number_in_old_list']
            if 'child_name' in self.changed_data:
                filter_kwargs[self.field_map['child_name']] = self.cleaned_data['child_name']
            if 'document_number' in self.changed_data:
                requestion_ct = ContentType.objects.get_for_model(Requestion)
                requestion_ids = EvidienceDocument.objects.filter(
                    content_type=requestion_ct,
                    document_number=self.cleaned_data['document_number'],
                    template__destination=REQUESTION_IDENTITY
                ).values_list('object_id', flat=True)
                filter_kwargs[self.field_map['document_number']] = requestion_ids
            return filter_kwargs


class QueueFilterForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(QueueFilterForm, self).__init__(*args, **kwargs)
        fields_order = [
            'requestion_number',
            'status',
            'area',
            'age_group',
            'benefit_category',
            'admission_date',
            'decision_date',
            'without_facilities',
        ]
        self.fields = reorder_fields(self.fields, fields_order)
        if 'not_appeared' in self.fields:
            del self.fields['not_appeared']
        admission_date_choices = [
            (year.year, year.year) for year in
            Requestion.objects.queue().dates('admission_date', 'year')]
        admission_date_choices = [('', '---------'),] + admission_date_choices
        self.fields['admission_date'].choices = admission_date_choices
        decision_date_choices = [
            (year.year,year.year) for year in
            Requestion.objects.queue().dates('decision_datetime', 'year')]
        decision_date_choices = [('', '---------'),] + decision_date_choices
        self.fields['decision_date'].choices = decision_date_choices
        
    requestion_number = forms.CharField(
        label=u'Номер заявки в системе', required=False,
        widget=forms.TextInput(attrs={'data-mask': REQUESTION_NUMBER_MASK}),
        help_text=u"Укажите номер заявки, к которой вы хотите перейти")
    not_appeared = forms.BooleanField(
        label=u'Показать только неявившиеся заявки', required=False,
        help_text=u"Отметьте для отображения неявившихся заявок из очереди")
    status = forms.MultipleChoiceField(
        label=u'Статус заявки', required=False, choices=STATUS_CHOICES_FILTER,
        help_text=u"При выборе в очереди будут отображаться заявки "
                  u"только с выбранным статусом")

sadiki/operator/views/base.py
# -*- coding: utf-8 -*-
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.utils.http import urlquote
from sadiki.core.models import Requestion, REQUESTION_IDENTITY
from sadiki.core.permissions import RequirePermissionsMixin
from sadiki.core.templatetags.sadiki_core_tags import FakeWSGIRequest

class OperatorPermissionMixin(RequirePermissionsMixin):
    u"""
    проверка является ли пользователь оператором
    """
    required_permissions = ['is_operator']


class OperatorRequestionMixin(OperatorPermissionMixin):

    def check_permissions(self, request, requestion, *args, **kwargs):
        if OperatorPermissionMixin.check_permissions(self, request) and request.user.perms_for_area(requestion.areas.all()):
            return True
        return False

    def dispatch(self, request, requestion_id, *args, **kwargs):
        requestion = get_object_or_404(Requestion, id=requestion_id)
        return RequirePermissionsMixin.dispatch(self, request, *args,
            requestion=requestion, **kwargs)


class OperatorRequestionCheckIdentityMixin(object):
    u"""проверяем, что у заявки указан идентифицирующий документ,
    если нет, то редирект на страницу с возможностью указать"""

    def dispatch(self, request, requestion_id, *args, **kwargs):
        requestion = get_object_or_404(Requestion, id=requestion_id)
        if not isinstance(request, FakeWSGIRequest):
            if requestion.is_fake_identity_documents:
                return HttpResponseRedirect(
                    u'%s?next=%s' %
                    (reverse('operator_requestion_set_identity_document',
                        kwargs={'requestion_id': requestion_id}),
                        urlquote(request.get_full_path()))
                    )
        return RequirePermissionsMixin.dispatch(self, request, *args,
            requestion=requestion, **kwargs)


class OperatorRequestionEditMixin(OperatorRequestionMixin):
    def check_permissions(self, request, requestion, *args, **kwargs):
        return super(OperatorRequestionEditMixin, self).check_permissions(
            request, requestion, *args, **kwargs) and requestion.editable

sadiki/anonym/templates/anonym/base.html
{% extends 'base.html' %}

{% block content_title %}<h1>{% block title %}Электронная очередь в ДОУ{% endblock %}</h1>{% endblock %}

sadiki/anonym/templates/anonym/frontpage.html
{% extends 'anonym/base.html' %}
{% load sadiki_core_tags %}

{% block content_header %}{% endblock %}

{% block css %}
    {{ block.super }}
    {% include "includes/leaflet_css.html" %}
{% endblock %}

{% block bottomjs %}
{% load_settings %}
    {% include "includes/leaflet_js.html" %}
    <script type="text/javascript">
        $(function(){
            var lonlat = [{{ settings.MAP_CENTER }}];
            lonlat.reverse();
            var map = new L.Map("map", {
                center: L.latLng(lonlat),
                zoom: {{ settings.MAP_ZOOM }}
            });
            var activeSadikIcon = L.icon({
                iconUrl: '{{ STATIC_URL }}img/sadik-icon.png',

                iconSize:     [22, 23], // size of the icon
                iconAnchor:   [11, 11], // point of the icon which will correspond to marker's location
                shadowAnchor: [4, 62]  // the same for the shadow
            });
            var osmLayer = new L.TileLayer("{{ settings.LEAFLET_TILES_URL }}", {
                subdomains: {{ settings.LEAFLET_TILES_SUBDOMAINS|safe }},
                attribution: 'Map data © OpenStreetMap contributors',
                center: L.latLng(lonlat),
                zoom: {{ settings.MAP_ZOOM }}
            });
            osmLayer.addTo(map);
        
            function renderMarkers(markers, map) {
                var markersLayer = new L.MarkerClusterGroup({
                    maxClusterRadius: 30
                });
                for (var i=0; i<markers.length; i++) {
                    var m = L.marker(markers[i].location.reverse(), {
                        title: markers[i].name,
                        icon: activeSadikIcon
                    });
                    m.bindPopup('<b>'+markers[i].name+'</b><div>Адрес: '+markers[i].address+'</div><div>Телефон: '+ markers[i].phone +'</div><a href="'+ markers[i].url +'">Перейти к ДОУ</a>');
                    markersLayer.addLayer(m);
                }
                map.addLayer(markersLayer);
            }
        
            function fetchSadiks(map) {
                $.ajax({
                    type: 'json',
                    url: '/api/sadiki.json'
                })
                .success(function(data){
                    renderMarkers(data, map);
                });
            }
        
            fetchSadiks(map);
        
        });
    </script>
<script type="text/javascript"> 
var $buoop = {}; 
$buoop.ol = window.onload; 
window.onload=function(){ 
 try {if ($buoop.ol) $buoop.ol();}catch (e) {} 
 var e = document.createElement("script"); 
 e.setAttribute("type", "text/javascript"); 
 e.setAttribute("src", "{{ STATIC_URL }}js/update.js"); 
 document.body.appendChild(e); 
} 
</script> 
{% endblock %}

{% block content %}
{#    <div class="center-aligned">#}
        <div id="map"></div>
{#    </div>#}
{% endblock %}

sadiki/anonym/templates/anonym/queue.html
{% extends "anonym/queue_base.html" %}
{% load sadiki_core_tags zenforms paginate %}

{% block bottomjs %}
  {{ block.super }}
  <script type="text/javascript">
    $(function(){
        {% if target_requestion %}
        $(window).scrollTo('#target', {offset:{top:-$(window).height()/2}, left:0});
        $('#id_requestion_number').parent('.ctrlHolder').append(' <a href="#target">Перейти к заявке</a>');
        {% endif %}

        $('<div id="up"><i class="icon-arrow-up"></i> Наверх</div>').insertAfter('ul.nav');
        $('#up').topLink({
            min: $('ul.nav').height() + $('.header').height(),
            fadeSpeed: 100
        }).click(function(e){
            e.preventDefault();
            $.scrollTo(0,300);
        });
    });

    $(document).ready(function(){
       $('label[for="id_age_group"]').append(' <span id="filter-age" class="icon-question-sign"></span>');
        {% queue_tooltips as tooltips %}
       $("label[for='id_age_group'] .icon-question-sign").popover({
            title: "Возрастные группы в системе",
            content: "{{ tooltips.age_groups_tooltip }}",
            placement: "top", html:true});
    });

    $('label[for="q_map"]').click(function(){
      $('label[for="q_map"]').off('click');
      $('#q_list').attr('checked', false);
      $('#q_map').attr('checked', true);
      location.href = '{% url "queue_map" %}?' + $('form').serialize();
      return false;
    })

    // отключаем кнопку после нажатия
    $('#export_to_excel').click(function() {
        $(this).addClass("disabled");
        $(this).prop("disabled", true);
        $('#xls').val('xls');
        $('.queue-forms form').submit();
        $('#xls').val('');
        return false;
    });

    $(".uniForm fieldset")
        .children().eq(2).nextAll()
        .wrapAll("<div class=\"spoiler\"></div>");

    $(".spoiler")
        .hide()
        .before('<a href="#" id="open_spoiler"> \
                    Расширенный поиск\
                    <span class="caret caret-margins caret-right"></span> \
                </a>');

    $("#open_spoiler").click(function(e){
        e.preventDefault();
        $(".spoiler").slideToggle();
        $(this).children("span").toggleClass("caret-right");
    });
  </script>

{% endblock %}

{% block content_title %}
    <h1>{% block title %}Очередь в ДОУ {{ area }}{% endblock %}</h1>
{% endblock %}

{% block content %}
    {{ block.super }}
    {% if not import_finished %}
        <div class="alert">
            Внимание! В очереди не отображаются заявки, поданные до запуска
            системы, они появятся позднее.
        </div>
    {% endif %}
        <div class="queue-forms clearfix" id="filterForm">
            <form action="." method="get" class="uniForm">
            {% izenform form options notag=1 nocsrf=1 %}
            {% if request.user.is_administrative_person %}
            <input id="xls" type="hidden" name="type" value="" />
            <p class="formHint">Для экспорта отфильтрованных заявок в Excel-файл, необходимо чтобы результат
            фильтрации возвращал не более 5000 заявок.</p>
            {% endif %}
            <div class="buttonHolder">
                <div id="view-switch" class="register-switch pull-left">
                  <input type="radio" name="view-type" value="L" id="q_list" class="register-switch-input" checked>
                  <label for="q_list" class="register-switch-label"><i class="icon-list"></i> Список</label>
                  <input type="radio" name="view-type" value="M" id="q_map" class="register-switch-input">
                  <label for="q_map" class="register-switch-label"><i class="icon-globe"></i> Карта</label>
                </div>
                <button class="primaryAction" value="submit"><i class="icon-filter"></i> Применить фильтр</button>
                {% if request.user.is_administrative_person %}
                <button id="export_to_excel"><i class="icon-download-alt"></i> Экспорт в Excel</button>
                {% endif %}
            </div>
            </form>
        </div>
    {% if requestions %}
        <div class="pagination-page">
            {% digg_paginator %}
        </div>

        {% with requestions as object_list %}
        {% block queue_table %}
            {% include 'anonym/includes/queue_include.html' %}
        {% endblock queue_table %}
        {% endwith %}

        <div class="pagination-page">
            {% digg_paginator %}
        </div>
    {% else %}
        <h2 class="vertical-margins center-aligned">Нет ни одной заявки в очереди, соответствующей вашему запросу</h2>
    {% endif %}

{% endblock %}

sadiki/anonym/templates/anonym/queue_base.html
{% extends "anonym/base.html" %}
{% load flatpages sadiki_core_tags %}

{% block css %}
    {{ block.super }}
    <link href="{{ STATIC_URL }}css/plugins/multiple-select.css" rel="stylesheet"/>
{% endblock css %}

{% block bottomjs %}
    {{ block.super }}
    <script defer type="text/javascript" src="{{ STATIC_URL }}js/libs/bootstrap-popover.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}/js/jquery.multiple.select.js"></script>
    <script>
        $('#id_status').multipleSelect({
            placeholder: "Выберите статусы из списка",
            selectAllText: "Выбрать все",
            allSelected: "Выбраны все статусы",
            countSelected: "# из % выбрано",
            width:'53%',
        });
        $('#id_area').multipleSelect({
            placeholder: "Выберите группы ДОУ из списка",
            selectAllText: "Выбрать все",
            allSelected: "Выбраны все группы ДОУ",
            countSelected: "# из % выбрано",
            width:'53%',
        });
    </script>
{% endblock %}

{% block content_menu %}
    {% url 'anonym_queue' as queue_url %}
    {% url 'queue_map' as queue_map_url %}
    {% url 'anonym_requestion_search' as requestion_search_url %}
    <ul class="content-menu">
        {% if queue_url|check_url_availability:request.user %}
            <li {% if request.path == queue_url or request.path == queue_map_url %}class="active"{% endif %}>
                <a href="{{ queue_url }}">Очередь</a>
            </li>
        {% endif %}
        {% if requestion_search_url|check_url_availability:request.user %}
            <li {% if request.path == requestion_search_url %}class="active"{% endif %}>
                <a href="{{ requestion_search_url }}">Поиск заявки</a>
            </li>
        {% endif %}
        {% get_flatpages "/queue_howto/" as queue_howto_pages %}
        {% if queue_howto_pages %}
            <li {% if request.path == queue_howto_pages.0.url %}class="active"{% endif %}>
                <a href="{{ queue_howto_pages.0.url }}">{{ queue_howto_pages.0.title }}</a>
            </li>
        {% endif %}
    </ul>
{% endblock %}

sadiki/anonym/templates/anonym/registration.html
{% extends "anonym/registration_base.html" %}

{% load zenforms %}

{% block content_title %}<h1>{% block title %}Регистрация пользователя{% endblock %}</h1>{% endblock %}

{% block content %}
    <div class="row registration-content">
        <div class="span6 right-split">
            <form id="mainform" class="uniForm registrationForm" action="." method="post" >
                {% if registration_form.non_field_errors %}
                    <div id="errorMsg">
                        {% load i18n %}
                        <h3>{% blocktrans count registration_form.non_field_errors|length as counter %}Please correct the error below.{% plural %}Please correct the errors below.{% endblocktrans %}</h3>
                        <ol>
                            {% for error in registration_form.non_field_errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ol>
                    </div>
                {% endif %}
                <h2>Создание профиля</h2>
                {% zenform registration_form options notag=1 %}
                    {% fieldset 'password1' 'password2' %}
                    <div class="permission-checkbox">
                        {% fieldset 'pdata_processing_permit' %}
                    </div>
                    <p class="hint">
                        В соответствии с Федеральным законом № 152-ФЗ от 27.07.2006 года
                        «О персональных данных» выражаю свое согласие на обработку
                        (сбор, систематизацию, накопление, хранение, уточнение, обновление, изменение),
                        использование способами, не противоречащими закону, моих персональных данных
                        (паспортных данных) и данных моего ребенка (данных свидетельства о рождении).
                        Обработка моих персональных данных будет производиться с целью предоставления
                        муниципальной услуги «Прием заявлений, постановка на учет и зачисление детей
                        в образовательные учреждения, осуществляющие образовательную деятельность
                        по программам дошкольного образования, присмотр и уход за детьми»
                        через ведомственную информационную систему «Электроочередь».
                    </p>
                    <p class="hint">
                        После регистрации вам будет присвоено Имя пользователя. Пожалуйста, запомните его и используйте в дальнейшем для входа в «Электроочередь».
                    </p>
                    {% submit "Зарегистрироваться" %}
                {% endzenform %}
            </form>
        </div>

        <div class="span5">
            <h2>Внешние источники</h2>

            {% if 'esia_auth' in special_apps %}
            <div class="social-auth-group">
                <div class="service-icon">
                    <img src="{{ STATIC_URL }}img/esia-large.png"/>
                </div>
                <div class="registration">
                    <a class="auth-link" href="{% url 'esia_authenticate' %}">
                        ЕСИА
                    </a>
                    <p class="hint">Регистрация через Единую Систему Идентификации и Аутентификации (ЕСИА).
                    При регистрации будет автоматически создан новый профиль в «Электроочереди».</p>
                </div>
            </div>
            {% endif %}

            <div class="social-auth-group">
                <div class="service-icon">
                    <img src="{{ STATIC_URL }}img/vkontakte-large.png"/>
                </div>
                <div class="registration">
                    <a class="auth-link" href="{% url 'social_auth:login' 'vkontakte-oauth2' %}">
                        ВКонтакте
                    </a>
                    <p class="hint">Если у вас есть профиль в социальной сети ВКонтакте, вы можете использовать
                    его для регистрации в «Электроочереди». При регистрации ваш аккаунт в социальной сети
                    остается в безопасности. Вам не нужно сообщать «Электроочереди» свой пароль от социальной сети,
                    необходимо только разрешить доступ к самым общим данным о вас.
                    Кроме того, в любой момент вы можете отвязать доступ «Электроочереди» от вашего профиля.</p>
                </div>
            </div>


        </div>
    </div>
{% endblock %}

{% block bottomjs %}
{{ block.super }}
    <script>
    $(document).ready(function() {
        $('#mainform button:submit').prop('disabled', !$('#id_pdata_processing_permit').is(':checked'));

        $('#id_pdata_processing_permit').on('click', function() {
          $('#mainform button:submit').prop('disabled', !$('#id_pdata_processing_permit').is(':checked'));
        });
    });
    </script>
{% endblock %}